name: roundcube
descr: Web-based IMAP email client with modern interface
page: https://roundcube.net
category: communication
default-credentials: use email account credentials
services:
  roundcubedb:
    image: docker.io/library/postgres:alpine
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  roundcubemail:
    image: docker.io/roundcube/roundcubemail:latest-fpm-alpine
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PORT=5432
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=changeme
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.example.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://smtp.example.com
      - ROUNDCUBEMAIL_SMTP_PORT=465
    depends_on:
      - roundcubedb
    volumes:
      - www:/var/www/html
    restart: unless-stopped

  roundcubenginx:
    image: docker.io/library/nginx:alpine
    ports:
      - 3017:80:web
    depends_on:
      - roundcubemail
    volumes:
      - www:/var/www/html:ro
    configs:
      - source: 'nginx_conf'
        target: '/etc/nginx/conf.d/default.conf'
    restart: unless-stopped
configs:
  'nginx_conf':
    content: |
      server {
          listen 80;
          server_name _;
          root /var/www/html;
          index index.php;

          location / {
              try_files $uri $uri/ /index.php?$args;
          }

          location ~ \.php$ {
              fastcgi_pass roundcubemail:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }

          location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml|woff|woff2)$ {
              expires 30d;
              access_log off;
          }
      }