name: openwebui
descr: User-friendly WebUI for LLMs (formerly Ollama WebUI)
page: https://github.com/open-webui/open-webui
category: ai
default-credentials: web setup
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3003:8080:web
    volumes:
      - data:/app/backend/data
    environment:
      OPENAI_API_KEY: your_secret_key
