name: searxng
descr: Privacy-respecting, hackable metasearch engine
page: https://github.com/searxng/searxng
category: search
services:
  redis:
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey-data:/data
    restart: unless-stopped
  server:
    image: docker.io/searxng/searxng:latest
    ports:
      - 8089:8080:web
    environment:
      SEARXNG_BASE_URL: http://[accessIP]:[accessPort]/
      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml
    volumes:
      - searxng-config:/etc/searxng
      - searxng-data:/var/cache/searxng
    restart: unless-stopped