name: frigate
descr: an open source NVR built around real-time AI object detection. All processing is performed locally on your own hardware, and your camera feeds never leave your home.
page: https://frigate.video
category: video
services:
  frigate:
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - config:/config
      - storage:/media/frigate
    ports:
      - "5000:5000:web"
      - "8971:8971:web-https"
      - "8554:8554:RTSP"
      - "8555:8555/tcp:WebRTC"
      - "8555:8555/udp:WebRTC"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
